### ISSUE TITLE
Incorrect URL decoding in PactBrokerClient when fetching pacts

### ISSUE THREAD

**Issue by mszczygiel** [pact-foundation/pact-jvm#1154] opened 2020-07-02 07:10 UTC
Hello,
While versioning contracts, we append git branch name to the version so we always have separate contract per branch. Unfortunately, when version contains special characters (like '/' in my case) fetching pacts via `PactBrokerClient.fetchLatestConsumersWithNoTag` or `PactBrokerClient.fetchConsumersWithSelectors` fails with `au.com.dius.pact.core.pactbroker.NotFoundHalResponse: No HAL document found at path ...`. For example for response from the broker containing:
```json
{
"href": "http://broker-url/pacts/provider/provider.name/consumer/consumer.name/version/3.0.2-SNAPSHOT-feature%2F123",
"title": "title",
"name": "consumer.name"
}
```
`PactBrokerClient` would go to
`http://broker-url/pacts/provider/provider.name/consumer/consumer.name/version/3.0.2-SNAPSHOT-feature/123` which is incorrect in this case.
Pact jvm version that we're using is 4.0.10, but I can see nothing has changed in this area on current master.

It seems that `href` decoding is unnecessary, if you agree (or have other suggestion on how to approach it) then I'm happy to contribute a fix for that.

**Comment by uglyog** [comment] 2020-07-12 02:29
The problem is that if we don't decode the URL, when the HTTP client encodes it before sending the request, and it will end up double encoded.

**Comment by uglyog** [comment] 2020-08-09 07:42
4.1.7 has been released with this fix

**Closed** 2021-04-21 04:56 UTC
Labels: bug
