### ISSUE TITLE
Setting a consumer branch name, support in pact-jvm 4.3.x

### ISSUE THREAD

**Issue by johnreilly100** [pact-foundation/pact-jvm#1501] opened 2022-01-07 13:54 UTC
Cant find any other place to ask this question so sorry in advance if its not the correct place.

Can the branch be set when using pact-jvm 4.3.x for a consumer. I can set a branch for a provider with `-Dpact.provider.branch` but I cant find any similar property for the consumer. I am aware of the pact broker setting `PACT_BROKER_USE_FIRST_TAG_AS_BRANCH` that can be used to use the tag name as the branch name but I want to be able to set the branch with a property. I have checked out the code and it seems its not available yet is this the case?

Setting `PACT_BROKER_USE_FIRST_TAG_AS_BRANCH` = `false` causes no branch property to be set at all for pact broker version 2.93.2.

**Comment by uglyog** [comment] 2022-01-10 00:43
Duplicate of #1453

**Closed** 2022-01-12 14:52 UTC
