### ISSUE TITLE
@PactFolder doesn't work correctly with absolute path

### ISSUE THREAD

**Issue by ghost** [pact-foundation/pact-jvm#236] opened 2016-04-02 08:15 UTC
Simple switching from @PactFolder to @PactUrl makes it work
- Working: @PactUrl(urls = {"file:///Users/HL/tmp/pacts/hello_consumer-hello_provider.json"})
- Not working: @PactFolder("/Users/HL/tmp/pacts/hello_consumer-hello_provider.json")
  I noticed that when debugging, the "path" in the later case is read as empty value. I have discussed with @uglyog and here's his suggestion:

> @luvLinux I have found the issue. @PactFolder loads the pacts from a resource folder via class.getClassLoader().getResource(). If you put your directory in a project resource folder (for example src/test/resources/pacts) and then use @PactFolder("pacts") it will work.

For reference, working source code is here, but I had to use @PackUrl
Test file in Java: https://gist.github.com/luvLinux/188394b94e98ad3716f9864d3a882f06
Pact file in JSON: https://gist.github.com/luvLinux/fc38200a2b08f767017b55eae2579a90

**Comment by uglyog** [comment] 2016-04-10 01:49
`@PactFolder` loader will load pacts from a directory now.

**Comment by uglyog** [comment] 2016-05-04 06:16
This has been released with versions 3.2.7 and 2.4.9

**Comment by tspoeri** [comment] 2017-07-13 16:12
The fix does not work on Windows (tested with `au.com.dius:pact-jvm-provider-spring_2.11:3.5.1`). 

When defining e.g. `@PactFolder("src/test/resources/pact_contracts")` then no pact files are found (`java.lang.Exception: Did not find any pact files for provider Xyz`)

The problem is in method `au.com.dius.pact.provider.junit.loader.PactFolderLoader.resolvePath()` on line 74:
&nbsp;&nbsp;&nbsp;&nbsp;`URL resourcePath = PactFolderLoader.class.getClassLoader().getResource(path.getPath());`

`path.getPath()` returns `"src\test\resources\pact_contracts"` which results in `resourcePath` being set to `"file:/C:/path/to/project/src%5ctest%5cresources%5cpact_contracts"` which does not correspond with the folder defined in the annotation.

To fix this, the backslashes '\\' in the value returned by `path.getPath()` have to be converted to forward slashes '/', e.g. `path.getPath().replace('\\', '/')`

**Comment by uglyog** [comment] 2017-07-16 23:05
Re-opening this to resolve issues with Windows.

**Comment by uglyog** [comment] 2017-12-08 02:56
I can not reproduce this issue (with the latest version). Have a look at [AmqpTest](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-junit/src/test/java/au/com/dius/pact/provider/junit/AmqpTest.java), it works on Windows.

**Comment by lonofit** [comment] 2018-05-15 07:28
Unfortunately the issue explaned by @tspoeri still exists on Windows. I updated vom 2.4.19 to 3.5.15 and got "Did not find any pact files for provider". A quick debug confirms that `/`s result in `%5c`s in the resourcePath. My workaround was to move all pact file to a path without slashes...

**Comment by uglyog** [comment] 2021-08-01 04:05
Closing this issue as I can't replicate it.

Tested with 4.2.9 with Java 11.0.10 on Windows 10 with https://github.com/pact-foundation/pact-jvm/blob/master/provider/spring/src/test/java/au/com/dius/pact/provider/spring/BooksPactProviderTest.java


@PactFolder("pacts")
```
Verifying a pact between Authors-Service and Books-Service
  [Using File C:\Users\uglyo\Development\Projects\Pact\pact-jvm\provider\spring\build\resources\test\pacts\authors-contract.json]
  Given create-book-bad-data
  Add book bad data
  Add book bad data
```

@PactFolder("src/test/resources/pacts")
```
Verifying a pact between Authors-Service and Books-Service
  [Using File src\test\resources\pacts\authors-contract.json]
  Given create-book
  Add book
  Add book
```

@PactFolder("C:\\Users\\uglyo\\Development\\Projects\\Pact\\pact-jvm\\provider\\spring\\src\\test\\resources\\pacts")
```
Verifying a pact between Authors-Service and Books-Service
  [Using File C:\Users\uglyo\Development\Projects\Pact\pact-jvm\provider\spring\src\test\resources\pacts\authors-contract.json]
  Given create-book
  Add book
  Add book
```

@PactFolder("C:/Users/uglyo/Development/Projects/Pact/pact-jvm/provider/spring/src/test/resources/pacts") also works

**Closed by uglyog** 2021-08-01 04:05 UTC
Labels: bug
