### ISSUE TITLE
Pact Gradle plugin causes build to fail since 4.3.13

### ISSUE THREAD

**Issue by wojniemiec** [pact-foundation/pact-jvm#1588] opened 2022-08-05 07:12 UTC
Hello, after upgrading Pact gradle plugin to 4.3.13 (from 4.3.12) our gradle build fails almost immediately after starting it.

The error I got:
Could not apply requested plugin [id: ‘au.com.dius.pact’, version: ‘4.3.13’] as it does not provide a plugin with id ‘au.com.dius.pact’. This is caused by an incorrect plugin implementation. Please contact the plugin author(s)

Version 4.3.12 works perfectly fine. :)

**Comment by rholshausen** [comment] 2022-08-08 00:46
How are you applying the plugin to the project?

**Comment by rholshausen** [comment] 2022-08-08 00:52
Also, can you let us know what version of Gradle you are using?

**Comment by diptee-warudkar** [comment] 2022-08-08 13:03
Same for us. 

We are using gradle-7.4.2.  

build.gradle ->

buildscript {
    repositories {
        mavenCentral()
    }
}
plugins {
    id 'au.com.dius.pact' version '4.3.13'
} 
.....


Error->
Could not apply requested plugin [id: 'au.com.dius.pact', version: '4.3.13'] as it does not provide a plugin with id 'au.com.dius.pact'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
> Plugin with id 'au.com.dius.pact' not found.

**Comment by rholshausen** [comment] 2022-08-10 05:41
If you remove `mavenCentral()` from the build script repositories, it will then work.

**Comment by wojniemiec** [comment] 2022-08-10 06:50
Hello @rholshausen , we are using gradle 7.4.2.
Also, we are not using mavenCentral() as repository, we are using our own nexus repositories (but I suppose they fetch most of the dependencies from central repo).

**Comment by rholshausen** [comment] 2022-08-10 07:03
The problem is that the plugin needs to be fetched from plugins.gradle.org, not from a Maven repository.

The next released version should be fixed and be able to be loaded from a Maven repository.

**Comment by christiansiegel** [comment] 2022-08-29 05:23
Thanks for fixing this with 4.3.14. However, the `gradle` plugin artifact was not released on Maven Central: https://mvnrepository.com/artifact/au.com.dius.pact.provider/gradle

**Comment by rholshausen** [comment] 2022-08-30 06:22
The gradle artifact is there now: https://repo1.maven.org/maven2/au/com/dius/pact/provider/gradle/4.3.14/

**Closed by rholshausen** 2022-08-30 06:22 UTC
Labels: bug
