### ISSUE TITLE
JUnit failing with requests not received

### ISSUE THREAD

**Issue by lordofthejars** [pact-foundation/pact-jvm#349] opened 2016-12-02 09:50 UTC
Hello, I am facing one problem that maybe it is normal but I would like to be sure that it is not a bug. Currently I have my JUnit test that defines the PactFragment like:

```
return builder
                .uponReceiving("User older than PEGI description")
                    .path("/checker/")
                    .method("POST")
                    .headers(headers)
                    .body(toJson(
                            "{                  " +
                            "  'age': 18,       " +
                            "  'pegi': 'PEGI_16'" +
                            "}")
                    )
                .willRespondWith()
                    .status(200)
                    .body("OK", ContentType.TEXT_PLAIN)
                .uponReceiving("User younger than PEGI description")
                .path("/checker/")
                .method("POST")
                .headers(headers)
                .body(toJson(
                        "{                  " +
                                "  'age': 16,       " +
                                "  'pegi': 'PEGI_18'" +
                                "}")
                )
                .willRespondWith()
                .status(200)
                .body("NO_OK", ContentType.TEXT_PLAIN)
            .toFragment();
```

So as you can see this fragment contains two interactions.

Then I have two tests, one that tests the first `uponReceiving` part and another one that tests the second `uponReceiving` interaction.

The problem is that when you run the first test it fails because the second interaction were not received and the same for the second one against the first.

So if you want to use this approach you need to create a single test that verifies at the same test both scenarios, which it seems a bad practice in terms of writing tests since in theory in each test you should only test one thing, but in this case you are testing two things.

```
@Test
public void test() {
  testYoungerThanPegi();
  testOlderThanPegi();
}
```

Notice that you are asserting two different scenarios in same test instead of:

```
@Test
public void test1() {
  testYoungerThanPegi();
}
@Test
public void test2() {
  testOlderThanPegi();
}
```

Notice that now each tests asserts one thing.

So obviously the solution I have found for now is to use several fragments so each test verifies one thing. Is this the expected behaviour to work with?

**Comment by PierreVincent** [comment] 2016-12-02 19:13
Yes in my experience this is the expected way to write your consumer test. 

You are testing 2 different behaviours here, they are both on the same end-point but you are expecting different responses.

When defining your consumer-side tests, you should only specify the interactions that happen for that given test, not all possible interactions and leave the test "pick and choose". In my opinion it makes it clearer in the test which consumer actions/requests tie in with expected provider behavior.

**Comment by lordofthejars** [comment] 2016-12-02 21:19
I agree, but I think validation should be at class test level instead of
method test level.

**Comment by uglyog** [comment] 2016-12-10 23:05
The problem is that the mock server has no idea which response to return. By using separate tests with only the expected requests for that test, there is no issue.

We could make requests optional, but then you lose the ability to detect that a request was missing (for instance if someone commented out some critical branch in the code).

**Comment by lordofthejars** [comment] 2016-12-11 08:52
yes , I agree with you but what I mean is that maybe he validation should be class aware, so after executing all test of the class, then you validate this calling a method. Maybe even a method called validate that checks if everything has been called. Then users can decide if to use in method level, class level, suite level or never (although it has no sense).

**Comment by uglyog** [comment] 2016-12-14 10:05
I'll have to give this some thought, it is a bit different from how all the pact tests have been designed.

**Comment by lordofthejars** [comment] 2017-01-21 11:58
Hi, I know what you mean, the problem is that from my point of view (which of course it doesn't mean it is the only one valid), a test method should test one thing, so one test method for testing the main path, another test method to test missing parameter, another test method to test internal error, ...

Of course you can do this by using pact fragments, but maybe it would be great to support this approach out of the box and do the interaction validation after the whole test class and not after test method. If you need help we can work together on this.

**Comment by uglyog** [comment] 2017-01-25 23:59
I think this is achievable but running all the tests, then injecting a surrogate test at the end that validates the state of the mock server. It will definitely give much better feedback, and could resolve #304

**Comment by uglyog** [comment] 2021-08-01 04:32
The way to test this scenario to to define two different tests, one for each interaction. Both interactions will be merged into the pact file. There is a check that will fail the tests if any of the interactions are not executed.

**Closed by uglyog** 2021-08-01 04:32 UTC
Labels: enhancement
