### ISSUE TITLE
Integer don't match Integer

### ISSUE THREAD

**Issue by Slatibartfass** [pact-foundation/pact-jvm#542] opened 2017-09-19 09:05 UTC
I have a consumer test
`PactDslWithProvider pact = ConsumerPactBuilder.consumer("yyy").hasPactWith("xxx");
PactFragment fragment = pact.given(...)
...
.willRespondWith()
.status(200)
.body(new PactDslJsonBody()
  .array("hits")
    .object()
      .object("document")
        .object("details")
          .integerType("year_from")
          .integerType("year_to")
        .closeObject()
      .closeObject()
    .closeObject()
  .closeArray())
.toFragment();`

resulting in a PACT file
`{
  "provider": {
    "name": "xxx"
  },
  "consumer": {
    "name": "yyy"
  },
  "interactions": [
    {
      "description": "any request",
      "request": {
        "method": "POST",
        "path": "anypath",
        "headers": {
          "Content-Type": "application/json"
        },
        "body": {
          "record_info": [
            "details.year_from",
            "details.year_to"
          ]
        },
      },
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json; charset=UTF-8"
        },
        "body": {
          "hits": [
            {
              "document": {
                "details": {
                  "year_from": 429513805,
                  "year_to": 657549309
                }
              }
            }
          ]
        },
        "matchingRules": {
          "$.body.hits[0].document.details.year_from": {
            "match": "integer"
          },
          "$.body.hits[0].document.details.year_to": {
            "match": "integer"
          }
        }
      },
      "providerState": "Test"
    }
  ],
  "metadata": {
    "pact-specification": {
      "version": "2.0.0"
    },
    "pact-jvm": {
      "version": "3.3.4"
    }
  }
}`

Running a provider test with this PACT file results in:
$.hits.0.document.details.year_to -> Expected 657549309to be an integer
$.hits.0.document.details.year_from -> Expected 429513805to be an integer

Any suggestions what's wrong here?

**Comment by GrythaOgg** [comment] 2017-09-19 15:24
To me it looks like this issue has the same reason as #209
At least for the groovy implementation (au.com.dius.pact.consumer.groovyMatchers) the matcher for integer is implemented as:
```
private static final int TEN = 10

  static integer(Long value = null) {
    new TypeMatcher(values: ['integer', value ?: RandomStringUtils.randomNumeric(TEN) as Long])
  }
```
so a 10 digit random is generated and used which likely calculated to be to bigger than max Integer **2147483647**

**Comment by Slatibartfass** [comment] 2017-09-20 05:40
Sorry, that's not the solution.
Both integers hve 9 digits.
Nevertheless I changed the values to 2015 and 2019.
Nothing really changes:
`$.hits.0.document.my_datev.year_to -> [{mismatch=Expected 2017.0 to be an integer, diff=}]
$.hits.0.document.my_datev.year_from -> [{mismatch=Expected 2015.0 to be an integer, diff=}]`
Any othe suggestions?

**Comment by GrythaOgg** [comment] 2017-09-20 06:06
Sorry but, when you are dealing with type-safety. You don’t have to count number of digits. You have to deal with mathematic. As I said maximum I integer is   2147483647

Obviously:  657549309 > 429513805 > 2147483647

Thus, both numbers have 9 Digits but are surly NOT an integer.

What ever happened to 2015 and 2019. The error message tells 
Expected were 2017.0 and 2017.0

These are floating points and no integers

**Comment by Slatibartfass** [comment] 2017-09-20 06:28
Sorry, but I can't follow you.
As you said, 2,147,483,647 is MAXINT.
But 657,549,309 and 429,513,805 are both much smaller than this. So why aren't they integers?

The real problem: excpected are integers, but the test gets floats.
The values in the PACT file are 2015 and 2019 without tailing ".0".
The matchingrule
"$.body.hits[0].document.details.year_to": { "match": "integer" }
declares them as integer.
So for me, it's all correct. Everything is integer.
But somewhere while processing the test, the Java "numbers" (so Java only knows numbers) aren't converted to integer.
I can't see why.

**Comment by GrythaOgg** [comment] 2017-09-20 08:21
Oh yes you re right, my second post was nonsense. I was too focused on my problem with the code described in my first post :-(

**Comment by uglyog** [comment] 2017-10-02 02:44
@Slatibartfass what version of Pact-JVM are you using?

**Comment by ogallon** [comment] 2019-01-15 16:56
+1 integers does not match for me

**Comment by uglyog** [comment] 2019-02-16 04:03
@ogallon could you provide more information?

**Comment by poojashukla9219** [comment] 2019-05-29 07:56
Facing the same issue with pact jvm version 3.6.6 and pact-ruby-standalone version 1.66.0.
Using integerType method while defining contract,
`integerType("start", 123)`

This is added correctly in pact file,
`"$.body.data.start": {
                        "match": "integer"
                    }` 

Getting this warning while running pact verification (using pact-ruby-standalone version 1.66.0),
`WARN: Ignoring unsupported matching rules {"match"=>"integer"} for path $['body']['result']['end']
WARN: Ignoring unsupported matching rules {"match"=>"integer"} for path $['body']['result']['start']`

Can someone please look into this?

**Comment by uglyog** [comment] 2019-06-01 08:47
@poojashukla9219 pact-ruby-standalone does not support V3 matchers yet

**Comment by poojashukla9219** [comment] 2019-06-12 09:15
Thanks @uglyog

**Comment by AvantiJundare26** [comment] 2020-07-10 12:38
I am new to contract testing and implementing it for the first time . 
I am able to generate the pact which is having the matching rule ,but for the integertype the pact verification by the provider is failing giving the following message:
$.0.tenantId -> Expected 1001027 but received 100102

It is actually comparing the value instead of the datatype .
the matching rule for the response body in the pact is given below :

matchingRules": {
                    "body": {
                        "$$[0].tenantId": {
                            "matchers": [
                                {
                                    "match": "integer"
                                }
                            ],
                            "combine": "AND"
                        }

dependency used:

<dependency>
			<groupId>au.com.dius</groupId>
			<artifactId>pact-jvm-provider-spring_2.12</artifactId>
			<version>3.5.15</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>au.com.dius</groupId>
			<artifactId>pact-jvm-consumer-junit5_2.12</artifactId>
			<version>3.5.24</version>
			
		</dependency>
		<dependency>
			<groupId>au.com.dius</groupId>
			<artifactId>pact-jvm-provider-junit5_2.12</artifactId>
			<version>3.5.24</version>
			 <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
		</dependency>

**Comment by uglyog** [comment] 2020-07-25 03:42
This has been fixed in later versions, but the issue is probably you're receiving a string value, and the error message is not indicating that. In later versions (like 4.1.x), it would print `$.0.tenantId -> Expected 1001027 (Integer) but received '100102' (String)`

**Closed** 2023-11-15 05:04 UTC
