### ISSUE TITLE
Provider JVM client library @VersionSelector branch option

### ISSUE THREAD

**Issue by johnreilly100** [pact-foundation/pact-jvm#1505] opened 2022-01-12 12:12 UTC
version 4.3.4

Aa far as I can tell there is no way to select a specific branch with the `@VersionSelector` annotation under the `@PactBroker` one.
Is this the case or is there another way to select a specific consumer branch.

**Comment by uglyog** [comment] 2022-02-07 04:55
Duplicate of #1465

**Comment by uglyog** [comment] 2022-02-07 05:07
Just a note that the selectors can be overridden by supplying the raw JSON: #1471

**Closed** 2022-06-21 03:09 UTC
Labels: duplicate
