### ISSUE TITLE
NoSuchMethodError on PactDslJsonBody.booleanType

### ISSUE THREAD

**Issue by flexfrank** [pact-foundation/pact-jvm#1309] opened 2021-02-17 08:00 UTC
If `booleanType` is called in `object` in `array`, `NoSuchMethodError` is thrown.
I got this error with "au.com.dius.pact.consumer:java8:4.1.17" and "au.com.dius.pact.consumer:junit5:4.2.0".

This test code below can reproduce the error.
```kotlin
@ExtendWith(PactConsumerTestExt::class)
internal class BooleanTypeFailingTest {

    @Pact(provider = "serviceA", consumer = "serviceB")
    fun pact(builder: PactDslWithProvider): RequestResponsePact {
        return builder
            .given("foo")
            .uponReceiving("bar")
            .path("/v1/test")
            .method("POST")
            .body(
                LambdaDsl.newJsonBody {
                    it.array("array") { array ->
                        array.`object` { obj ->
                            obj.booleanType("boolean1", true)
                        }
                    }
                }.build()
            )
            .willRespondWith()
            .status(200)
            .toPact()
    }

    @Test
    @PactTestFor(providerName = "serviceA", port = "0", pactMethod = "pact")
    fun configDomain(mockServer: MockServer) {
    }
}
```

stacktrace:
```text
'au.com.dius.pact.consumer.dsl.PactDslJsonBody au.com.dius.pact.consumer.dsl.PactDslJsonBody.booleanType(java.lang.String, java.lang.Boolean)'
java.lang.NoSuchMethodError: 'au.com.dius.pact.consumer.dsl.PactDslJsonBody au.com.dius.pact.consumer.dsl.PactDslJsonBody.booleanType(java.lang.String, java.lang.Boolean)'
	at io.pactfoundation.consumer.dsl.LambdaDslObject.booleanType(LambdaDslObject.java:178)
	at BooleanTypeFailingTest$pact$1$1$1.accept(BooleanTypeFailingTest.kt:25)
	at BooleanTypeFailingTest$pact$1$1$1.accept(BooleanTypeFailingTest.kt:12)
	at io.pactfoundation.consumer.dsl.LambdaDslJsonArray.object(LambdaDslJsonArray.java:35)
	at BooleanTypeFailingTest$pact$1$1.accept(BooleanTypeFailingTest.kt:24)
	at BooleanTypeFailingTest$pact$1$1.accept(BooleanTypeFailingTest.kt:12)
	at io.pactfoundation.consumer.dsl.LambdaDslObject.array(LambdaDslObject.java:588)
	at BooleanTypeFailingTest$pact$1.accept(BooleanTypeFailingTest.kt:23)
	at BooleanTypeFailingTest$pact$1.accept(BooleanTypeFailingTest.kt:12)
	at io.pactfoundation.consumer.dsl.LambdaDsl.newJsonBody(LambdaDsl.java:75)
	at BooleanTypeFailingTest.pact(BooleanTypeFailingTest.kt:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.platform.commons.support.ReflectionSupport.invokeMethod(ReflectionSupport.java:198)
	at au.com.dius.pact.consumer.junit5.PactConsumerTestExt.lookupPact(PactConsumerTestExt.kt:345)
	at au.com.dius.pact.consumer.junit5.PactConsumerTestExt.setupMockServer(PactConsumerTestExt.kt:245)
	at au.com.dius.pact.consumer.junit5.PactConsumerTestExt.beforeTestExecution(PactConsumerTestExt.kt:233)
...snip
```

**Comment by flexfrank** [comment] 2021-02-17 08:20
`minArrayLike(java.lang.String, java.lang.Integer)` and `maxArrayLike(java.lang.String, java.lang.Integer)` also throw `NoSuchMethodError`

```kotlin
    @Pact(provider = "serviceA", consumer = "serviceB")
    fun min(builder: PactDslWithProvider): RequestResponsePact {
        return builder
            .given("foo")
            .uponReceiving("bar")
            .path("/v1/test")
            .method("POST")
            .body(
                LambdaDsl.newJsonBody {
                    it.minArrayLike("test", 0) {
                    }
                }.build()
            )
            .willRespondWith()
            .status(200)
            .toPact()
    }

    @Pact(provider = "serviceA", consumer = "serviceB")
    fun max(builder: PactDslWithProvider): RequestResponsePact {
        return builder
            .given("foo")
            .uponReceiving("bar")
            .path("/v1/test")
            .method("POST")
            .body(
                LambdaDsl.newJsonBody {
                    it.maxArrayLike("test", 0) {
                    }
                }.build()
            )
            .willRespondWith()
            .status(200)
            .toPact()
    }
```

**Comment by gmariotti** [comment] 2021-02-17 08:28
Following too, I have tests that fail because of `NoSuchMethodError` for `booleanType` and `minArrayLike`

**Comment by uglyog** [comment] 2021-02-20 03:56
Can you check your dependencies, `au.com.dius.pact.consumer:java8:4.1.17` requires `au.com.dius.pact.consumer:4.1.17`. If you have an older version of `au.com.dius.pact.consumer` loaded on your classpath, it could cause this issue.

**Comment by flexfrank** [comment] 2021-02-24 07:04
@uglyog 
I checked the dependencies and `au.com.dius.pact:consumer:4.2.0` is used.
It is imported by `au.com.dius.pact.consumer:junit5:4.2.0` implicitly.

**Comment by uglyog** [comment] 2021-03-03 22:38
Are you using Maven, or Gradle, or something else?

**Comment by uglyog** [comment] 2021-03-03 23:32
I created an example project https://github.com/uglyog/gradle-kotlin-test with your test. It works for me.

Please compare it to yours.

**Comment by gmariotti** [comment] 2021-03-04 15:54
I can confirm that, at least in Gradle, this is a transitive dependencies problem. `au.com.dius.pact.consumer:junit5:4.2.0` imports `au.com.dius.pact:consumer:4.2.0` which overrides the `au.com.dius.pact:consumer:4.1.7` set by `au.com.dius.pact.consumer:java8:4.1.7` and that would explain why the method with signature `minArrayLike(string, integer)` is now missing in the `PactDslJsonBody` class

**Comment by uglyog** [comment] 2021-03-06 23:13
Ah! `au.com.dius.pact.consumer:java8` has been merged into `au.com.dius.pact:consumer:4.2.0`, just remove that dependency.

**Closed by uglyog** 2021-03-06 23:13 UTC

**Comment by gmariotti** [comment] 2021-03-09 08:02
Thanks for the suggestion @uglyog 😅 I can confirm that removing the `java8` library and updating the imports, fixed the issue. I guess I missed the library deprecation 😓

**Comment by nagkumar** [comment] 2022-10-05 08:42
Yes, change these to 

```
import static io.pactfoundation.consumer.dsl.LambdaDsl.newJsonArrayMinLike;
import static io.pactfoundation.consumer.dsl.LambdaDsl.newJsonBody;
```

to 

import static au.com.dius.pact.consumer.dsl.LambdaDsl.newJsonArrayMinLike;
import static au.com.dius.pact.consumer.dsl.LambdaDsl.newJsonBody;
